language: java

jdk:
    - openjdk8
    - oraclejdk8
      
dist: trusty

addons:
    postgresql: "9.6"

# go faster on travis
sudo: false

# stop mvn install from running
install: true

script: ./mvnw -B -V package $( [[ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]] && echo javadoc:javadoc ) test

after_success:
    - ./mvnw -B -V clean test jacoco:report coveralls:report
